### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by aispin** [Tingglelaoo/wxtoken#1]
有几个问题，你可以优化下的：
### 1. Token类

方法应尽量定义在prototype里面，现在你大部分写在Token那个构造函数里面了，扣性能细节的话会影响Token类的实例化性能
### 2. 刷新缓存的策略

现在用了轮询检查刷新的方法，其实可以不用轮询的。每次从服务端获取Token的时候，

2.1 看是否有文件缓存

2.2 如果没有，则从服务器端获取，并存入缓存

2.3 如果有，拿（当前时间戳 - 已缓存的Token的时间戳），看是否超出过期时间

2.3.1 如果超出过期时间，进入2.2

2.3.2 如果没过期，直接返回缓存的Token
### 3. auth.js 不属于路由

新建一个utils的目录，将auth.js放到utils目录下
### 4. 新建一个configs/config.js文件

配置类型的信息都可以放config.js中
即将 APPID和APPSECRET抽到config.js中

```
module.exports = {
    APPID: process.env.APP_ID
    APPSECRET: process.env.APP_SECRET
};
```

**Comment by Tingglelaoo** [comment]
针对上面四点，已经更新为2.0版本啦
